<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.haoric</groupId>
    <artifactId>haoric-ddd</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>haoric-ddd</name>
    <description>
        面向 Spring Boot 的 DDD 框架与开发工具集 / DDD architecture for Spring Boot
    </description>

    <url>https://github.com/org-haoric/haoric-ddd</url>
    <inceptionYear>2024</inceptionYear>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>haoric-haozhi</id>
            <name>Deng Haozhi</name>
            <url>https://github.com/haoric-haozhi</url>
            <organization>haoric-org</organization>
            <organizationUrl>https://github.com/haoric-org</organizationUrl>
            <roles>
                <role>developer</role>
                <role>maintainer</role>
            </roles>
        </developer>
    </developers>

    <scm>
        <connection>
            scm:git:git://github.com/spring-projects/org-haoric/haoric-ddd.git
        </connection>
        <developerConnection>
            scm:git:ssh://git@github.com/org-haoric/haoric-ddd.git
        </developerConnection>
        <url>https://github.com/org-haoric/haoric-ddd</url>
    </scm>

    <modules>
        <module>haoric-ddd-generator</module>
        <module>haoric-ddd-starters</module>
        <module>haoric-ddd-sidecar</module>
    </modules>

    <properties>

        <!-- Project -->
        <java.version>25</java.version>
        <encoding>UTF-8</encoding>
        <project.build.sourceEncoding>${encoding}</project.build.sourceEncoding>
        <project.reporting.outputEncoding>${encoding}</project.reporting.outputEncoding>

        <!-- Maven -->
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven-compiler-plugin.version>3.16.0</maven-compiler-plugin.version>

        <!-- Framework -->
        <spring-boot.version>4.1.1</spring-boot.version>
        <druid.version>1.2.28</druid.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
        <pagehelper.version>4.1.1</pagehelper.version>

        <!-- Infrastructure -->
        <minio.version>9.0.3</minio.version>
        <okhttp.version>5.5.0</okhttp.version>
        <sqlite.version>3.50.3.0</sqlite.version>

        <!-- Utils -->
        <bcprov.version>1.86</bcprov.version>
        <fastjson2.version>2.0.65</fastjson2.version>
        <snakeyaml.version>2.7</snakeyaml.version>

        <!-- Development -->
        <lombok.version>1.18.48</lombok.version>
    </properties>

    <!-- 依赖声明 -->
    <dependencyManagement>
        <dependencies>
            <!-- Haoric DDD -->
            <dependency>
                <groupId>org.haoric</groupId>
                <artifactId>haoric-ddd-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- Framework -->
            <!-- SpringBoot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Druid -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <!-- Mybatis Plus -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <!-- Page Helper -->
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>

            <!-- Infrastructure -->
            <!-- MinIO -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.squareup.okhttp3</groupId>
                        <artifactId>okhttp</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp-jvm</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <!-- Sqlite -->
            <dependency>
                <groupId>org.xerial</groupId>
                <artifactId>sqlite-jdbc</artifactId>
                <version>${sqlite.version}</version>
            </dependency>

            <!-- Utils -->
            <!-- Bouncy Castle -->
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov.version}</version>
            </dependency>
            <!-- Fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <!-- SnakeYAML -->
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>${snakeyaml.version}</version>
            </dependency>

            <!-- Dev -->
            <!-- Lombok -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                        <release>${maven.compiler.release}</release>
                        <encoding>${encoding}</encoding>
                        <parameters>${maven.compiler.parameters}</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
